# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: npm install # runs during prebuild
    command: npm start
  - name: Initialize AWS CLI
    command: bash $GITPOD_REPO_ROOT/AWSCLI.sh
  - name: Initialize AWS CLI
    command: gp idp login aws --role-arn <981241700645> [--duration-seconds=<3600>] aws secretsmanager get-secret-value --secret-id database_connection_string --region us-east-1 | jq .SecretString

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
