image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  # runs during prebuild
  - init: |
      npm install
      npm install aws-amplify
      npm install @aws-amplify/ui-react aws-amplify
      npm install react@latest react-dom@latest
     # runs after prebuild
    command: npm start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
